version: "3.8"
services:
  crypt-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    user: "root"
    ports:
      - "8080:3838"
    volumes:
      - "./app:/home/app"
